version: '2'
services:
  widget:
    image: garystafford/widget:latest
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    hostname: "widget"
    container_name: "widget"
    environment:
      - NODE_ENV=production
      - NODE_HOST=localhost
      - NODE_PORT=3000
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - LOG_LEVEL=trace
  mongodb:
    image: mongo:3.3
    ports:
      - "27018:27017"
    volumes:
      - /data/db:/data/db
    restart: always
    hostname: "mongodb"
    container_name: "mongodb"