version: '2'
services:
  widget:
    image: garystafford/widget:latest
    expose:
      - "3001"
    ports:
      - "3001:3000"
    links:
      - mongodb:mongodb
    depends_on:
      - mongodb
    hostname: "widget"
    container_name: "widget"
    environment:
      - NODE_ENV=production
      - NODE_HOST=127.0.0.1
      - NODE_PORT=3001
      - MONGO_HOST=127.0.0.1
      - MONGO_PORT=27018
      - LOG_LEVEL=trace
  mongodb:
    image: mongo:3.3
    ports:
      - "27018:27017"
    expose:
      - "27018"
    volumes:
      - /data/db:/data/db
    restart: always
    hostname: "mongodb"
    container_name: "mongodb"